package com.ssm.mapper;

import com.ssm.bean.Permission;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    int deleteByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    Permission selectByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    List<Permission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    int updateByPrimaryKey(Permission record);
}