package com.ssm.mapper;

import com.ssm.bean.Role;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    int deleteByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    Role selectByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    int updateByPrimaryKey(Role record);

    /**
     * 通过用户名来获取对应的角色
     * @param userName
     * @return
     */
    List<Role> listAllRoleByUser(String userName);
}