package com.ssm.mapper;

import com.ssm.bean.User;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    User selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    int updateByPrimaryKey(User record);

    /**
     * 通过用户名来获取包含角色和权限的用户信息
     *
     * @param userName
     * @return
     */
    User getUserWithRoleAndPermission(String userName);

    /**
     * 通过用户名获取用户
     * @param userName
     * @return
     */
    User getUserByName(String userName);

    String isExitUser(String userName);
}