package com.ssm.bean;

import java.io.Serializable;

public class Permission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PermissionId
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    private Integer permissionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PermissionName
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    private String permissionname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PermissionId
     *
     * @return the value of permission.PermissionId
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PermissionId
     *
     * @param permissionid the value for permission.PermissionId
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PermissionName
     *
     * @return the value of permission.PermissionName
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public String getPermissionname() {
        return permissionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PermissionName
     *
     * @param permissionname the value for permission.PermissionName
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public void setPermissionname(String permissionname) {
        this.permissionname = permissionname == null ? null : permissionname.trim();
    }
}