package com.ssm.bean;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.Permission_Id
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    private Integer permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.Permission_Name
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    private String permissionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.Permission_Id
     *
     * @return the value of permission.Permission_Id
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.Permission_Id
     *
     * @param permissionId the value for permission.Permission_Id
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.Permission_Name
     *
     * @return the value of permission.Permission_Name
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.Permission_Name
     *
     * @param permissionName the value for permission.Permission_Name
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }
}