package com.ssm.bean;

import java.io.Serializable;

public class Role implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.RoleId
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.RoleName
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.RoleId
     *
     * @return the value of role.RoleId
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.RoleId
     *
     * @param roleid the value for role.RoleId
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.RoleName
     *
     * @return the value of role.RoleName
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.RoleName
     *
     * @param rolename the value for role.RoleName
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }
}