package com.ssm.bean;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.Role_Id
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.Role_Name
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.Role_Id
     *
     * @return the value of role.Role_Id
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.Role_Id
     *
     * @param roleId the value for role.Role_Id
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.Role_Name
     *
     * @return the value of role.Role_Name
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.Role_Name
     *
     * @param roleName the value for role.Role_Name
     *
     * @mbggenerated Fri May 10 19:49:32 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}