package com.ssm.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class User implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserId
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.User
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.QQ
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.salt
     *
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    private String salt;


    private List<Role> roleList = new ArrayList<>();

    private List<Permission> permissionList = new ArrayList<>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserId
     *
     * @return the value of user.UserId
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserId
     *
     * @param userid the value for user.UserId
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.User
     *
     * @return the value of user.User
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.User
     *
     * @param user the value for user.User
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password
     *
     * @return the value of user.Password
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password
     *
     * @param password the value for user.Password
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.QQ
     *
     * @return the value of user.QQ
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.QQ
     *
     * @param qq the value for user.QQ
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.salt
     *
     * @return the value of user.salt
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.salt
     *
     * @param salt the value for user.salt
     * @mbggenerated Thu Sep 20 11:57:29 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    public List<Role> getRoleList() {
        return roleList;
    }

    public void setRoleList(List<Role> roleList) {
        this.roleList = roleList;
    }

    public List<Permission> getPermissionList() {
        return permissionList;
    }

    public void setPermissionList(List<Permission> permissionList) {
        this.permissionList = permissionList;
    }

    public String getCredentialsSalt() {
        return this.user + this.salt;
    }
}